<a href="https://colab.research.google.com/github/SanghunOh/test_deeplearning/blob/main/diff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sigmoid

In [2]:
import tensorflow as tf

In [6]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [7]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [8]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

#softmax

In [13]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.60339683, -0.26259094, -0.9843191 ]], dtype=float32)>

In [14]:
outputs = tf.keras.activations.softmax(inputs)
# outputs

In [15]:
outputs.numpy()

array([[0.32369673, 0.4551436 , 0.22115965]], dtype=float32)