In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [58]:
note_seq[0:5]

['g8', 'e8', 'e4', 'f8', 'd8']

In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
len(note_seq), range(len(note_seq)-4) # [4,8,12,....]

(54, range(0, 50))

In [5]:
code2idx['g8']

11

In [6]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [7]:
import numpy as np
datasets = np.array(dataset)

In [8]:
x_train = datasets[:,0:3]
x_train.shape, #x_train

((50, 3),)

In [9]:
y_train = datasets[:,3]
y_train.shape, #y_train

((50,),)

In [10]:
len(code2idx)

14

In [11]:
x_train = x_train / 13 # len(code2idx)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [12]:
import tensorflow as tf

In [13]:
x_train.shape, x_train[2] # --> scale


((50, 3), array([0.15384615, 0.76923077, 0.61538462]))

In [20]:
X_train = np.reshape(x_train, (-1, 3, 1)) # tensor
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [15]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [38]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(3,1))) # input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [55]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10) # 50 / 5 = 10

Epoch 1/500
5/5 [==============================] - 0s 5ms/step - loss: 1.2017 - accuracy: 0.5400
Epoch 2/500
5/5 [==============================] - 0s 5ms/step - loss: 1.1958 - accuracy: 0.5400
Epoch 3/500
5/5 [==============================] - 0s 6ms/step - loss: 1.2133 - accuracy: 0.5000
Epoch 4/500
5/5 [==============================] - 0s 6ms/step - loss: 1.2023 - accuracy: 0.5400
Epoch 5/500
5/5 [==============================] - 0s 6ms/step - loss: 1.1916 - accuracy: 0.5200
Epoch 6/500
5/5 [==============================] - 0s 6ms/step - loss: 1.2075 - accuracy: 0.5200
Epoch 7/500
5/5 [==============================] - 0s 5ms/step - loss: 1.2010 - accuracy: 0.5600
Epoch 8/500
5/5 [==============================] - 0s 5ms/step - loss: 1.1935 - accuracy: 0.5400
Epoch 9/500
5/5 [==============================] - 0s 6ms/step - loss: 1.1875 - accuracy: 0.5400
Epoch 10/500
5/5 [==============================] - 0s 5ms/step - loss: 1.1983 - accuracy: 0.5400
Epoch 11/500
5/5 [===========

In [41]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 9ms/step - loss: 2.2991 - accuracy: 0.3400


[2.2991223335266113, 0.3400000035762787]

In [50]:
X_train[0:1]

array([[[0.84615385],
        [0.69230769],
        [0.15384615]]])

In [51]:
model.predict(X_train[0:1])

array([[0.06276721, 0.07326367, 0.06615437, 0.06334293, 0.06808366,
        0.05769436, 0.05563723, 0.07428502, 0.10730358, 0.13512774,
        0.08318092, 0.09876675, 0.05439264]], dtype=float32)

In [46]:
first = 0.61538462
second = 0.07692308
third = 0.53846154

In [56]:
pred = model.predict(X_train[0:1])

In [57]:
np.argmax(pred)

10

In [ ]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [ ]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']