<a href="https://colab.research.google.com/github/SanghunOh/learn_NaturalLanguageProcessing/blob/main/codes/word_representatioin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 기본 토큰화 

In [1]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [9]:
sentence = "I'm, we're, rock 'n' roll"
sentence = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."
sentence = "m.p.h, Ph.D나 AT&T"
word_tokenize(sentence)

['m.p.h', ',', 'Ph.D나', 'AT', '&', 'T']

In [8]:
from nltk.tokenize import sent_tokenize
sentence = "I am actively looking for Ph.D. students. and you are a Ph.D student"
sentence = "IP 231.68.56.31 에 들어가서 로그 파일 저장해 otter@gmail.com로 보내줘"
sentence = "I'm actively looking for Ph.D. students, I get the same question."
sent_tokenize(sentence)

["I'm actively looking for Ph.D. students, I get the same question."]

## 한글 토큰화 and 품사 달기

nltk : PRP(인칭 대명사), VBP(동사), RB(부사), VBG(현재부사), IN(전치사), NNP(고유 명사), NNS(복수형 명사), CC(접속사), DT(관사)

In [14]:
from nltk.tokenize import word_tokenize
text="열심히 코딩한 당신, 연휴에는 여행을 가봐요."
from nltk.tag import pos_tag
nltk.download('averaged_perceptron_tagger')
x=word_tokenize(text)
print(pos_tag(x))
# [('열심히', 'JJ'), ('코딩한', 'NNP'), ('당신', 'NNP'), (',', ','), ('연휴에는', 'NNP'), ('여행을', 'NNP'), ('가봐요', 'NNP'), ('.', '.')]

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[('열심히', 'JJ'), ('코딩한', 'NNP'), ('당신', 'NNP'), (',', ','), ('연휴에는', 'NNP'), ('여행을', 'NNP'), ('가봐요', 'NNP'), ('.', '.')]


In [15]:
!python -m pip install konlpy 


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.4 MB 3.8 MB/s 
     |████████████████████████████████| 453 kB 41.9 MB/s 


In [16]:
from konlpy.tag import Okt  
okt=Okt();			print(okt.morphs(text))
# ['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']  
print(okt.pos(text))  
# [('열심히','Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]  
print(okt.nouns(text))  

['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요', '.']
[('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb'), ('.', 'Punctuation')]
['코딩', '당신', '연휴', '여행']


##word onehotencoding with tensorflow

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer
text="댓글은 인터넷 게시물 밑에 남길 수 있는 짧은 글이다."
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text]);		tokenizer.word_index;		
# {'게시물': 3, '글이다': 9, '남길': 5, '댓글은': 1, '밑에': 4, '수': 6, '인터넷': 2, '있는': 7, '짧은': 8}
sub_text="유즈넷(USENET) 시절 'reply'를 '리플라이', '답장' 등으로 사용하였다"	
tokenizer.texts_to_sequences([sub_text])[0]
# []									# 사전 있는 것만 확인 가능

[]

In [22]:
sub_text="보통 인터넷 게시물 밑에는 댓글란이 있어 그 게시물과 관련하여 독자는 의견을 표할 수 있다"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
# [2, 3, 6]
import tensorflow as tf

print(tf.keras.utils.to_categorical(encoded))
# [[0. 0. 1. 0. 0. 0. 0.]
#  [0. 0. 0. 1. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 1.]]


[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


##원형복원

In [24]:
>>> from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
>>> n=WordNetLemmatizer()
>>> words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
>>> print([n.lemmatize(w) for w in words])


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [25]:
 from nltk.stem import PorterStemmer
>>> s=PorterStemmer()
>>> words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
>>> print([s.stem(w) for w in words])
['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']

['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']


['polici',
 'do',
 'organ',
 'have',
 'go',
 'love',
 'live',
 'fli',
 'die',
 'watch',
 'ha',
 'start']